/**
 * The README's elements-by-dialect table, generated from the element catalogue (ADR 0007): one
 * row per element type, one column per dialect a fence may name, saying how the dialect spells
 * the type, and a last column saying how it is drawn. Written between two marker comments in
 * `README.md`; `test/readme-table.test.ts` fails when the committed table is stale.
 *
 * Usage: npm run readme:table
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CATALOGUE } from '../src/catalogue/index.js';
import { DIALECTS, PUBLIC_DIALECTS } from '../src/catalogue/dialects.js';
import type { DialectId, Draw, ElementType, Select, Spelling } from '../src/catalogue/types.js';

export const START = '<!-- elements-by-dialect: generated by npm run readme:table from src/catalogue/; do not edit -->';
export const END = '<!-- elements-by-dialect: end -->';

const DIALECT_NAMES: Readonly<Record<DialectId, string>> = {
  ngspice: 'ngspice', ltspice: 'LTspice', pspice: 'PSpice', hspice: 'HSPICE', xyce: 'Xyce', spectre: 'Spectre', 'spectre-spice': 'Spectre (SPICE mode)'
};

const code = (text: string): string => `\`${text}\``;
const list = (items: readonly string[]): string => items.map(code).join(', ');

/** What tells the type apart from the others sharing its letter, as a phrase after the letter. */
function selection(letter: string, select: Select): string {
  switch (select.by) {
    case 'model-type': {
      const types = list(select.types);
      return select.levels ? `${code(letter)} with a ${types} model at level ${select.levels.join(' or ')}` : `${code(letter)} with a ${types} model`;
    }
    case 'suffix': return list(select.suffixes.map((suffix) => `${letter}${suffix}`));
    case 'keyword': return `${code(letter)} with ${list(select.keywords)}`;
    case 'pair': return `${code(letter)} with ${list(select.keys.map((key) => `${key}=`))}`;
  }
}

function spellingText(spelling: Spelling): string {
  if (spelling.dialect === 'spectre') return spelling.master === '*' ? 'any other master' : code(spelling.master);
  return spelling.select ? selection(spelling.letter, spelling.select) : code(spelling.letter);
}

/** How one dialect spells the type: its plain letters or masters first, then the spellings a selector tells apart. */
export function cell(type: ElementType, dialect: DialectId): string {
  const spellings = type.spellings.filter((spelling) => spelling.dialect === dialect);
  if (spellings.length === 0) return '—';
  const plain = spellings.filter((spelling) => spelling.dialect === 'spectre' || spelling.select === undefined);
  const selected = spellings.filter((spelling) => spelling.dialect !== 'spectre' && spelling.select !== undefined);
  const groups = [plain.map(spellingText).join(', '), selected.map(spellingText).join('; ')].filter((group) => group !== '');
  return groups.join('; ');
}

export function drawnAs(draw: Draw): string {
  if (draw === 'none') return 'nothing: a coupling, noted';
  if ('symbol' in draw) {
    if (typeof draw.symbol === 'string') return `the ${code(draw.symbol)} symbol`;
    const { default: fallback, byModelType = {}, byModelFlag = {}, byModelParameter = {} } = draw.symbol;
    const others = new Set([...Object.values(byModelType), ...Object.values(byModelFlag), ...Object.values(byModelParameter).flatMap((values) => Object.values(values))]);
    others.delete(fallback);
    return others.size === 0 ? `the ${code(fallback)} symbol` : `the ${code(fallback)} symbol, or ${list([...others].sort())} by its model`;
  }
  const { title, polarity, pins } = draw.block;
  let text: string;
  if (typeof title === 'object') text = `a block titled ${code(title.fixed)}`;
  else {
    const by: Record<Exclude<typeof title, { fixed: string }>, string> = {
      'model-type': 'its model type', suffix: 'its type', keyword: 'its keyword', 'keyword-with-arguments': 'its keyword and arguments', master: 'the subcircuit or master name'
    };
    text = `a block titled by ${by[title]}`;
  }
  if (polarity) text += `, its polarity from the model`;
  if (pins === 'numbered') text += ', pins numbered';
  else if (pins === 'subcircuit-ports') text += ', pins named by the definition';
  else if (pins === 'xspice-ports') text += ', pins as XSPICE names them';
  else if (pins === 'hide-tied-to-common') text += ', a pin tied to the common not drawn';
  return text;
}

/** The whole table, element types sorted by name, for the catalogue given. */
export function table(catalogue: Readonly<Record<string, ElementType>>, dialects: readonly DialectId[] = PUBLIC_DIALECTS): string {
  const header = ['Element', ...dialects.map((dialect) => DIALECT_NAMES[dialect]), 'Drawn as'];
  const rows = Object.values(catalogue)
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
    .map((type) => [type.name, ...dialects.map((dialect) => cell(type, dialect)), drawnAs(type.draw)]);
  return [header, header.map(() => '---'), ...rows].map((row) => `| ${row.join(' | ')} |`).join('\n') + '\n';
}

/** The README section between the markers: an intro line, then the table. */
export function section(catalogue: Readonly<Record<string, ElementType>> = CATALOGUE): string {
  const count = Object.keys(catalogue).length;
  return [
    START,
    '',
    `<details><summary>Every element type the catalogue knows — ${count} of them — and how each dialect spells it</summary>`,
    '',
    'A letter alone is the whole spelling; "with" names the model type, keyword or `key=` pair that',
    'tells the type from others sharing the letter. Spectre spells by master name. Generated from',
    '`src/catalogue/` by `npm run readme:table`.',
    '',
    table(catalogue).trimEnd(),
    '',
    '</details>',
    '',
    END
  ].join('\n');
}

/** `readme` with the section between the markers replaced; throws when a marker is missing. */
export function splice(readme: string, generated: string): string {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start < 0 || end < start) throw new Error(`README.md lacks the markers ${START} … ${END}`);
  return readme.slice(0, start) + generated + readme.slice(end + END.length);
}

function main(): void {
  const file = fileURLToPath(new URL('../README.md', import.meta.url));
  const readme = readFileSync(file, 'utf8');
  const updated = splice(readme, section());
  if (updated === readme) console.log('README.md: elements-by-dialect table is current');
  else {
    writeFileSync(file, updated);
    console.log('README.md: elements-by-dialect table written');
  }
  // Every dialect in the table is one a fence may name.
  for (const dialect of PUBLIC_DIALECTS) if (DIALECTS[dialect].internal) throw new Error(`${dialect} is internal`);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) main();
